
services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: 25-12courses
    ports:
      - "5432:5432"
    volumes: 
      - db_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    
  apicore:
    image: shaibmen/online-courses:latest
    env_file:
      - ./online-courses/.env
    depends_on:
      - db
      - apiauth
    environment:
      DB: "host=db port=5432 user=postgres password=1 dbname=25-12courses sslmode=disable"
      LEVEL_LOG: Debug
      JWT_SECRET_KEY: gfhxg32q450uh3erfnsdf08najkytg49
      DB_USER: postgres
      DB_PASSWORD: 1
      DB_NAME: 25-12courses
      HOST: DB
    ports:
      - "8080:8080"

  apiauth:
    image: shaibmen/auth-service:latest
    env_file:
      - ./auth-service/.env
    depends_on:
      - db
    environment:
      DB: "host=db port=5432 user=postgres password=1 dbname=25-12courses sslmode=disable"
      JWT_SECRET_KEY: gfhxg32q450uh3erfnsdf08najkytg49
    ports:
      - "8081:8081"
    
  apidoc:
    image: shaibmen/document-service:latest
    env_file:
      - ./document-service/.env
    depends_on:
      - db
      - apiauth
      - apicore
    environment:
      PORT: :8082
    ports:
      - "8082:8082"

  frontend:
    image: shaibmen/online-courses-front:latest
    depends_on:
      - apicore
      - apiauth
      - apidoc
    ports:
      - "5173:80"
    environment:
      VITE_API1_URL: http://localhost:8080
      VITE_API2_URL: http://localhost:8081
      VITE_API3_URL: http://localhost:8082

volumes:
  db_data:
